# Generated by Django 4.0.4 on 2022-04-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positivecase',
            old_name='Date_Of_Diagonsis',
            new_name='Date_Of_Diagnosis',
        ),
    ]
